<?php

namespace Piwiweb\albumalbumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function findLatestAlbums($limit = 10, $public = true)
    {
        $qb = $this->createQueryBuilder('album');

        $qb->orderBy('album.date', 'ASC');
        $qb->setMaxResults($limit);
        if ($public === true) {
            $qb->where('album.public = 1');
        }

        return $qb->getQuery()->getResult();
    }
}
