<?php

namespace Piwiweb\PhotoalbumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function findLatestPhotos($limit = 10, $public = true)
    {
        $qb = $this->createQueryBuilder('photo');

        $qb->orderBy('photo.date', 'ASC');
        $qb->setMaxResults($limit);
        if ($public === true) {
            $qb->innerJoin('photo.album', 'album');
            $qb->where('album.public = 1');
        }

        return $qb->getQuery()->getResult();
    }
}
